import { Home, Users, GraduationCap, BookOpen, Calendar, FileText, Settings, Bell, School, ClipboardList, UserCog, Book, User, BarChart, MessageSquare, FolderOpen, DollarSign } from "lucide-react";

export const NAV_ITEMS = {
  admin: [
    { href: "/dashboard/admin", title: "Dashboard", icon: Home },
    { href: "/dashboard/admin/profile", title: "Profil Admin", icon: User },
    { href: "/dashboard/admin/students", title: "Kelola Siswa", icon: GraduationCap },
    { href: "/dashboard/admin/teachers", title: "Kelola Guru", icon: UserCog },
    { href: "/dashboard/admin/classes", title: "Kelola Kelas", icon: School },
    { href: "/dashboard/admin/subjects", title: "Mata Pelajaran", icon: Book },
    { href: "/dashboard/admin/schedules", title: "Jadwal", icon: Calendar },
    { href: "/dashboard/admin/users", title: "Kelola User", icon: Users },
    { href: "/dashboard/admin/announcements", title: "Pengumuman", icon: Bell },
    { href: "/dashboard/admin/reports", title: "Laporan", icon: BarChart },
    { href: "/dashboard/admin/settings", title: "Pengaturan", icon: Settings },
  ],
  teacher: [
    { href: "/dashboard/teacher", title: "Dashboard", icon: Home },
    { href: "/dashboard/teacher/profile", title: "Profil Saya", icon: User },
    { href: "/dashboard/teacher/schedule", title: "Jadwal", icon: Calendar },
    { href: "/dashboard/teacher/classes", title: "Kelas Saya", icon: School },
    { href: "/dashboard/teacher/attendance", title: "Absensi", icon: ClipboardList },
    { href: "/dashboard/teacher/assignments", title: "Tugas", icon: BookOpen },
    { href: "/dashboard/teacher/grades", title: "Input Nilai", icon: FileText },
    { href: "/dashboard/teacher/messages", title: "Pesan", icon: MessageSquare },
  ],
  student: [
    { href: "/dashboard/student", title: "Dashboard", icon: Home },
    { href: "/dashboard/student/profile", title: "Profil Saya", icon: User },
    { href: "/dashboard/student/schedule", title: "Jadwal", icon: Calendar },
    { href: "/dashboard/student/assignments", title: "Tugas", icon: BookOpen },
    { href: "/dashboard/student/materials", title: "Materi", icon: FolderOpen },
    { href: "/dashboard/student/grades", title: "Nilai", icon: FileText },
  ],
  parent: [
    { href: "/dashboard/parent", title: "Dashboard", icon: Home },
    { href: "/dashboard/parent/student-profile", title: "Profil Anak", icon: User },
    { href: "/dashboard/parent/attendance", title: "Absensi Anak", icon: ClipboardList },
    { href: "/dashboard/parent/grades", title: "Nilai Anak", icon: FileText },
    { href: "/dashboard/parent/messages", title: "Pesan", icon: MessageSquare },
    { href: "/dashboard/parent/announcements", title: "Pengumuman", icon: Bell },
  ],
  treasurer: [
    { href: "/dashboard/treasurer", title: "Dashboard", icon: Home },
    { href: "/dashboard/treasurer/profile", title: "Profil Saya", icon: User },
    { href: "/dashboard/treasurer/payments", title: "Pembayaran SPP", icon: DollarSign },
    { href: "/dashboard/treasurer/reports", title: "Laporan Keuangan", icon: BarChart },
    { href: "/dashboard/treasurer/messages", title: "Pesan", icon: MessageSquare },
  ],
};
